version: '3'

services:
    mongo:
        image: mongo
        environment:
#            MONGO_INITDB_ROOT_USERNAME: admin
#            MONGO_INITDB_ROOT_PASSWORD: admin!
            MONGO_INITDB_DATABASE: fastfood
        ports:
            - 27017:27017
        restart: unless-stopped
    mongo-express:
        image: mongo-express
        ports:
            - 8086:8081
        restart: unless-stopped
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: dev
            ME_CONFIG_BASICAUTH_PASSWORD: dev!
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin!
            ME_CONFIG_MONGODB_SERVER: mongo
        links:
            - mongo
        depends_on:
            - mongo